filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true
    prospector.scanner.symlinks: true
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_host_metadata: {}
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
